# Generated by Django 4.1.13 on 2024-10-07 13:17

import datetime
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='genre',
            field=models.CharField(choices=[('F', 'Feminin'), ('M', 'Masculin')], default=datetime.datetime(2024, 10, 7, 13, 17, 39, 646831, tzinfo=datetime.timezone.utc), max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='nationalite',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
