# Generated by Django 4.2.16 on 2024-10-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_connexion_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connexion',
            name='photo',
            field=models.ImageField(upload_to='logs'),
        ),
    ]
