# Generated by Django 5.1.6 on 2025-02-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_employe_is_deleted_marquerarrivee_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
