# Generated by Django 5.1.4 on 2025-03-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rapportmensuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='marquerarrivee',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
