# Generated by Django 5.1.6 on 2025-02-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_employe_isDeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marquerarrivee',
            name='isDeleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rapportmensuel',
            name='isDeleted',
            field=models.BooleanField(default=True),
        ),
    ]
