# Generated by Django 4.2.16 on 2024-11-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_marquerarrivee_latitude_marquerarrivee_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='adresse',
            field=models.TextField(),
        ),
    ]
