# Generated by Django 4.2.16 on 2024-11-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_employe_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='employe',
            name='matricule_employe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
