# Generated by Django 4.2.16 on 2024-11-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_employe_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
